{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diffkeeper.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: diffkeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
