version: "3.9"

services:
  nginx:
    build:
      context: ../..
      dockerfile: demo/nginx-cache-persist/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
      - "9912:9911"
    volumes:
      - nginx_deltas:/deltas
    depends_on:
      - backend

  backend:
    image: hashicorp/http-echo:1.0.0
    command: ["-listen", ":8080", "-text", "cache-me-if-you-can"]
    restart: unless-stopped

volumes:
  nginx_deltas:
