apiVersion: v1
kind: ServiceAccount
metadata:
  name: diffkeeper
  namespace: diffkeeper

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diffkeeper
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diffkeeper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diffkeeper
subjects:
  - kind: ServiceAccount
    name: diffkeeper
    namespace: diffkeeper
